export const SUBVARIATION_LIST_REQUEST = "SUBVARIATION_LIST_REQUEST";
export const SUBVARIATION_LIST_SUCCESS = "SUBVARIATION_LIST_SUCCESS";
export const SUBVARIATION_LIST_FAIL = "SUBVARIATION_LIST_FAIL";

export const SUBVARIATION_DETAILS_REQUEST = "SUBVARIATION_DETAILS_REQUEST";
export const SUBVARIATION_DETAILS_SUCCESS = "SUBVARIATION_DETAILS_SUCCESS";
export const SUBVARIATION_DETAILS_FAIL = "SUBVARIATION_DETAILS_FAIL";

export const SUBVARIATION_DELETE_REQUEST = "SUBVARIATION_DELETE_REQUEST";
export const SUBVARIATION_DELETE_SUCCESS = "SUBVARIATION_DELETE_SUCCESS";
export const SUBVARIATION_DELETE_FAIL = "SUBVARIATION_DELETE_FAIL";

export const SUBVARIATION_CREATE_REQUEST = "SUBVARIATION_CREATE_REQUEST";
export const SUBVARIATION_CREATE_SUCCESS = "SUBVARIATION_CREATE_SUCCESS";
export const SUBVARIATION_CREATE_FAIL = "SUBVARIATION_CREATE_FAIL";
export const SUBVARIATION_CREATE_RESET = "SUBVARIATION_CREATE_RESET";

export const SUBVARIATION_UPDATE_REQUEST = "SUBVARIATION_UPDATE_REQUEST";
export const SUBVARIATION_UPDATE_SUCCESS = "SUBVARIATION_UPDATE_SUCCESS";
export const SUBVARIATION_UPDATE_FAIL = "SUBVARIATION_UPDATE_FAIL";
export const SUBVARIATION_UPDATE_RESET = "SUBVARIATION_UPDATE_RESET";
