export const VARIATION_LIST_REQUEST = "VARIATION_LIST_REQUEST";
export const VARIATION_LIST_SUCCESS = "VARIATION_LIST_SUCCESS";
export const VARIATION_LIST_FAIL = "VARIATION_LIST_FAIL";

export const VARIATION_DETAILS_REQUEST = "VARIATION_DETAILS_REQUEST";
export const VARIATION_DETAILS_SUCCESS = "VARIATION_DETAILS_SUCCESS";
export const VARIATION_DETAILS_FAIL = "VARIATION_DETAILS_FAIL";

export const VARIATION_DELETE_REQUEST = "VARIATION_DELETE_REQUEST";
export const VARIATION_DELETE_SUCCESS = "VARIATION_DELETE_SUCCESS";
export const VARIATION_DELETE_FAIL = "VARIATION_DELETE_FAIL";

export const VARIATION_CREATE_REQUEST = "VARIATION_CREATE_REQUEST";
export const VARIATION_CREATE_SUCCESS = "VARIATION_CREATE_SUCCESS";
export const VARIATION_CREATE_FAIL = "VARIATION_CREATE_FAIL";
export const VARIATION_CREATE_RESET = "VARIATION_CREATE_RESET";

export const VARIATION_UPDATE_REQUEST = "VARIATION_UPDATE_REQUEST";
export const VARIATION_UPDATE_SUCCESS = "VARIATION_UPDATE_SUCCESS";
export const VARIATION_UPDATE_FAIL = "VARIATION_UPDATE_FAIL";
export const VARIATION_UPDATE_RESET = "VARIATION_UPDATE_RESET";
